### ISSUE TITLE
HLS manifests that include in-stream (subtitle) text track(s) fail to load on Chromecast (gen. 1)

### ISSUE THREAD

**Issue by warren-bank** [googlecast/CastReceiver#21] opened 2020-12-10 01:37 UTC
sample HLS manifests:
1. [https://cdn.theoplayer.com/video/elephants-dream/playlist-single-audio.m3u8](https://cdn.theoplayer.com/video/elephants-dream/playlist-single-audio.m3u8)
2. [https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8](https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8)

rather than going into [excruciating detail](https://github.com/warren-bank/clappr-chromecast-captions-plugin/issues/1), I'll summarize:
* tested on Chromecast gen. 1
* tested with:
  - Cast Receiver v2
  - Cast Receiver v3 (CAF)
  - `chrome.cast.media.DEFAULT_MEDIA_RECEIVER_APP_ID`
* sample streams won't play
  - other HLS manifests that don't include any in-stream (subtitle) text tracks do play well
    * this generalization also applies to HLS manifests that contain video streams with embedded/muxed closed captions

questions:
* is this a known issue or limitation
  - I only own gen. 1 devices and haven't tested on newer hardware, which shouldn't matter as this is clearly a software issue
* do these streams work for you?

- - - -

~~questions (not directly related to issue):~~
* ~~assuming this issue were fixed, what is the correct way for the sender to manage the visibility of in-stream (subtitle) text tracks?~~
  - ~~should the master manifest be parsed by the sender and the URL of each inner `#EXT-X-MEDIA:TYPE=SUBTITLES` manifest be added and managed as an [external text track](https://developers.google.com/cast/docs/chrome_sender/advanced)?~~
* ~~is there a similar API to manage the visibility of embedded/muxed closed captions?~~
  - ~~can they even be displayed on the Chromecast?~~

update: docs for the [TextTracksManager class](https://developers.google.com/cast/docs/web_receiver/tracks#closed_captions_subtitles) seems to answer these questions

**Comment by warren-bank** [comment] 2020-12-10 22:35
It's possible that I'm attributing these observations to the presence of in-stream subtitles only because that's the topic in which I'm currently working.

I just tested a completely unmodified copy of [the official reference sender app for Chrome](https://github.com/googlecast/CastVideos-chrome) that uses CAF APIs on both sender and receiver. None of the _.mp4_ media URLs play on any of my gen. 1 devices.

If I were to copy any of these _.mp4_ media URLs on a sender app for Chrome that doesn't use framework APIs (ex: [Clappr](https://github.com/clappr/clappr-chromecast-plugin)), it plays fine.

This new observation makes me think that something much more fundamental has recently been broken.. either in the receiver SDK, or possibly even in a recent firmware update.

Any insight?

**Comment by warren-bank** [comment] 2020-12-11 02:10
cross-reference: [issue](https://issuetracker.google.com/issues/175332497) added to tracker

**Comment by jtromo** [comment] 2021-04-08 22:58
Closing as the issue is being followed up in the tracker

**Closed by jtromo** 2021-04-08 22:58 UTC
